# Generated by Django 4.2.9 on 2024-09-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_googlesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesheet',
            name='sheet_id',
        ),
    ]
