# Generated by Django 4.2.9 on 2024-11-27 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlesheet',
            name='title',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
